-- TABELA Endereco
CREATE TABLE Endereco (
    ID_endereco NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    Rua    VARCHAR2(100),
    Numero VARCHAR2(10),
    Bairro VARCHAR2(50),
    Cidade VARCHAR2(50),
    CEP    VARCHAR2(9),

    CONSTRAINT PK_Endereco PRIMARY KEY (ID_endereco),
    CONSTRAINT CK_Endereco_CEP
      CHECK (CEP IS NULL OR REGEXP_LIKE(CEP, '^[0-9]{5}\-[0-9]{3}$')),
    CONSTRAINT CK_Endereco_Numero
      CHECK (Numero IS NULL OR REGEXP_LIKE(Numero, '^[0-9A-Za-z\s\-]+$'))
);
/

-- TABELA Fornecedor
CREATE TABLE Fornecedor (
    CNPJ          VARCHAR2(18) NOT NULL,
    Nome          VARCHAR2(100) NOT NULL,
    Tipo_fornecedor VARCHAR2(50) NOT NULL,
    Telefone      VARCHAR2(15),
    Razao_social  VARCHAR2(150) NOT NULL,

    CONSTRAINT PK_Fornecedor PRIMARY KEY (CNPJ),
    CONSTRAINT CK_Fornecedor_CNPJ
      CHECK (REGEXP_LIKE(CNPJ, '^[0-9]{2}\.[0-9]{3}\.[0-9]{3}/[0-9]{4}\-[0-9]{2}$')),
    CONSTRAINT CK_Fornecedor_Tipo
      CHECK (Tipo_fornecedor IN ('Editora','Distribuidor','Autor Independente','Importador')),
    CONSTRAINT CK_Fornecedor_Nome CHECK (LENGTH(Nome) >= 2),
    CONSTRAINT CK_Fornecedor_Telefone
      CHECK (Telefone IS NULL OR REGEXP_LIKE(Telefone, '^\([0-9]{2}\)[0-9]{4,5}-[0-9]{4}$'))
);
/

-- TABELA Livro
CREATE TABLE Livro (
    ID_livro NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    Autor    VARCHAR2(100) NOT NULL,
    Nome     VARCHAR2(200) NOT NULL,
    Categoria VARCHAR2(50) NOT NULL,
    Ano      NUMBER NOT NULL,
    Editora  VARCHAR2(100) NOT NULL,
    Preco    NUMBER(10,2) NOT NULL,

    CONSTRAINT PK_Livro PRIMARY KEY (ID_livro),
    CONSTRAINT CK_Livro_Ano CHECK (Ano BETWEEN 1450 AND 2100),
    CONSTRAINT CK_Livro_Preco CHECK (Preco > 0),
    CONSTRAINT CK_Livro_Nome CHECK (LENGTH(Nome)  >= 1),
    CONSTRAINT CK_Livro_Autor CHECK (LENGTH(Autor) >= 2),
    CONSTRAINT CK_Livro_Categoria CHECK (Categoria IN (
        'Ficção','Não-ficção','Romance','Suspense','Terror','Fantasia',
        'Biografia','História','Ciência','Autoajuda','Infantil','Juvenil','Técnico','Didático'))
);
/

-- TABELA Funcionario
CREATE TABLE Funcionario (
    ID_funcionario NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    Nome       VARCHAR2(100) NOT NULL,
    ID_endereco NUMBER,
    Salario    NUMBER(10,2) NOT NULL,
    Gerente    NUMBER,

    CONSTRAINT PK_Funcionario PRIMARY KEY (ID_funcionario),
    CONSTRAINT FK_Funcionario_Endereco FOREIGN KEY (ID_endereco)
        REFERENCES Endereco(ID_endereco),
    CONSTRAINT FK_Funcionario_Gerente FOREIGN KEY (Gerente)
        REFERENCES Funcionario(ID_funcionario),
    CONSTRAINT CK_Funcionario_Salario CHECK (Salario > 0),
    CONSTRAINT CK_Funcionario_Nome    CHECK (LENGTH(Nome) >= 2)
);
/

-- TABELA Cliente
CREATE TABLE Cliente (
    ID_cliente NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    Nome    VARCHAR2(100) NOT NULL,
    Email   VARCHAR2(100),
    Rua     VARCHAR2(100),
    Numero  VARCHAR2(10),
    Bairro  VARCHAR2(50),
    Cidade  VARCHAR2(50),
    CEP     VARCHAR2(9),
    Tipo    CHAR(1) NOT NULL,
    CPF_CNPJ VARCHAR2(18) NOT NULL,

    CONSTRAINT PK_Cliente PRIMARY KEY (ID_cliente),
    CONSTRAINT UK_Cliente_CPF_CNPJ UNIQUE (CPF_CNPJ),
    CONSTRAINT CK_Cliente_Tipo CHECK (Tipo IN ('F','J')),
    CONSTRAINT CK_Cliente_Nome CHECK (LENGTH(Nome) >= 2),
    CONSTRAINT CK_Cliente_Email
      CHECK (Email IS NULL OR REGEXP_LIKE(Email, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$')),
    CONSTRAINT CK_Cliente_CEP
      CHECK (CEP IS NULL OR REGEXP_LIKE(CEP, '^[0-9]{5}\-[0-9]{3}$')),
    CONSTRAINT CK_Cliente_Numero
      CHECK (Numero IS NULL OR REGEXP_LIKE(Numero, '^[0-9A-Za-z\s\-]+$')),
    CONSTRAINT CK_Cliente_CPF_CNPJ
      CHECK (
        (Tipo = 'F' AND REGEXP_LIKE(CPF_CNPJ, '^[0-9]{3}\.[0-9]{3}\.[0-9]{3}\-[0-9]{2}$')) OR
        (Tipo = 'J' AND REGEXP_LIKE(CPF_CNPJ, '^[0-9]{2}\.[0-9]{3}\.[0-9]{3}/[0-9]{4}\-[0-9]{2}$'))
      )
);
/

-- TABELA Pessoa_Fisica
CREATE TABLE Pessoa_Fisica (
    CPF        VARCHAR2(14) NOT NULL,
    ID_cliente NUMBER NOT NULL,

    CONSTRAINT PK_Pessoa_Fisica PRIMARY KEY (CPF),
    CONSTRAINT FK_Pessoa_Fisica_Cliente FOREIGN KEY (ID_cliente)
        REFERENCES Cliente(ID_cliente) ON DELETE CASCADE,
    CONSTRAINT CK_Pessoa_Fisica_CPF
      CHECK (REGEXP_LIKE(CPF, '^[0-9]{3}\.[0-9]{3}\.[0-9]{3}\-[0-9]{2}$'))
);
/

-- TABELA Pessoa_Juridica
CREATE TABLE Pessoa_Juridica (
    CNPJ       VARCHAR2(18) NOT NULL,
    ID_cliente NUMBER NOT NULL,

    CONSTRAINT PK_Pessoa_Juridica PRIMARY KEY (CNPJ),
    CONSTRAINT FK_Pessoa_Juridica_Cliente FOREIGN KEY (ID_cliente)
        REFERENCES Cliente(ID_cliente) ON DELETE CASCADE,
    CONSTRAINT CK_Pessoa_Juridica_CNPJ
      CHECK (REGEXP_LIKE(CNPJ, '^[0-9]{2}\.[0-9]{3}\.[0-9]{3}/[0-9]{4}\-[0-9]{2}$'))
);
/

-- TABELA Telefone_Cliente
CREATE TABLE Telefone_Cliente (
    ID_cliente NUMBER NOT NULL,
    Telefone   VARCHAR2(15) NOT NULL,

    CONSTRAINT PK_Telefone_Cliente PRIMARY KEY (ID_cliente, Telefone),
    CONSTRAINT FK_Telefone_Cliente FOREIGN KEY (ID_cliente)
        REFERENCES Cliente(ID_cliente) ON DELETE CASCADE,
    CONSTRAINT CK_Telefone_Cliente_Tel
      CHECK (REGEXP_LIKE(Telefone, '^\([0-9]{2}\)[0-9]{4,5}-[0-9]{4}$'))
);
/

-- TABELA Telefone_Funcionario
CREATE TABLE Telefone_Funcionario (
    ID_funcionario NUMBER NOT NULL,
    Telefone       VARCHAR2(15) NOT NULL,

    CONSTRAINT PK_Telefone_Funcionario PRIMARY KEY (ID_funcionario, Telefone),
    CONSTRAINT FK_Telefone_Funcionario FOREIGN KEY (ID_funcionario)
        REFERENCES Funcionario(ID_funcionario) ON DELETE CASCADE,
    CONSTRAINT CK_Telefone_Funcionario_Tel
      CHECK (REGEXP_LIKE(Telefone, '^\([0-9]{2}\)[0-9]{4,5}-[0-9]{4}$'))
);
/

-- TABELA Estoque
CREATE TABLE Estoque (
    ID_livro          NUMBER NOT NULL,
    Lote              VARCHAR2(20) NOT NULL,
    Quantidade_livro  NUMBER NOT NULL,
    Data_entrada      DATE NOT NULL,
    Data_saida        DATE,

    CONSTRAINT PK_Estoque PRIMARY KEY (ID_livro, Lote),
    CONSTRAINT FK_Estoque_Livro FOREIGN KEY (ID_livro)
        REFERENCES Livro(ID_livro) ON DELETE CASCADE,
    CONSTRAINT CK_Estoque_Qtd CHECK (Quantidade_livro >= 0),
    CONSTRAINT CK_Estoque_Datas CHECK (Data_saida IS NULL OR Data_saida >= Data_entrada),
    CONSTRAINT CK_Estoque_Lote CHECK (LENGTH(Lote) >= 1)
);
/

-- TRIGGER: impedir data_entrada futura
CREATE OR REPLACE TRIGGER trg_estoque_data
BEFORE INSERT OR UPDATE ON Estoque
FOR EACH ROW
BEGIN
    IF :NEW.Data_entrada > TRUNC(SYSDATE) THEN
        RAISE_APPLICATION_ERROR(-20001, 'Data_entrada não pode ser futura.');
    END IF;
END;
/
-- TABELA Venda
CREATE TABLE Venda (
    ID_venda     NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ID_cliente   NUMBER NOT NULL,
    ID_livro     NUMBER NOT NULL,
    ID_funcionario NUMBER NOT NULL,
    Data_venda   DATE NOT NULL,
    Quantidade   NUMBER NOT NULL,
    Valor_total  NUMBER(10,2) NOT NULL,
    Parcelamento NUMBER,
    Forma_pagamento VARCHAR2(50) NOT NULL,

    CONSTRAINT PK_Venda PRIMARY KEY (ID_venda),
    CONSTRAINT FK_Venda_Cliente FOREIGN KEY (ID_cliente) REFERENCES Cliente(ID_cliente),
    CONSTRAINT FK_Venda_Livro   FOREIGN KEY (ID_livro)   REFERENCES Livro(ID_livro),
    CONSTRAINT FK_Venda_Func    FOREIGN KEY (ID_funcionario) REFERENCES Funcionario(ID_funcionario),
    CONSTRAINT CK_Venda_Qtd   CHECK (Quantidade > 0),
    CONSTRAINT CK_Venda_Valor CHECK (Valor_total > 0),
    CONSTRAINT CK_Venda_Parc  CHECK (Parcelamento IS NULL OR Parcelamento >= 1),
    CONSTRAINT CK_Venda_Forma CHECK (Forma_pagamento IN ('Dinheiro','Cartão Débito','Cartão Crédito','PIX','Boleto','Transferência'))
);
/
-- TRIGGER: impedir Data_venda futura
CREATE OR REPLACE TRIGGER trg_venda_data
BEFORE INSERT OR UPDATE ON Venda
FOR EACH ROW
BEGIN
    IF :NEW.Data_venda > TRUNC(SYSDATE) THEN
        RAISE_APPLICATION_ERROR(-20002, 'Data_venda não pode ser futura.');
    END IF;
END;
/
-- TABELA Enviar
CREATE TABLE Enviar (
    CNPJ_fornecedor VARCHAR2(18) NOT NULL,
    ID_livro        NUMBER NOT NULL,
    Data_envio      DATE NOT NULL,
    Quantidade      NUMBER NOT NULL,
    Valor           NUMBER(10,2) NOT NULL,
    Codigo_envio    VARCHAR2(50) NOT NULL,

    CONSTRAINT PK_Enviar PRIMARY KEY (CNPJ_fornecedor, ID_livro, Data_envio),
    CONSTRAINT FK_Enviar_Fornecedor FOREIGN KEY (CNPJ_fornecedor) REFERENCES Fornecedor(CNPJ),
    CONSTRAINT FK_Enviar_Livro      FOREIGN KEY (ID_livro)        REFERENCES Livro(ID_livro),
    CONSTRAINT UK_Enviar_Codigo UNIQUE (Codigo_envio),
    CONSTRAINT CK_Enviar_Qtd   CHECK (Quantidade > 0),
    CONSTRAINT CK_Enviar_Valor CHECK (Valor > 0),
    CONSTRAINT CK_Enviar_Cod   CHECK (LENGTH(Codigo_envio) >= 5)
);
/
-- TRIGGER: impedir Data_envio futura
CREATE OR REPLACE TRIGGER trg_enviar_data
BEFORE INSERT OR UPDATE ON Enviar
FOR EACH ROW
BEGIN
    IF :NEW.Data_envio > TRUNC(SYSDATE) THEN
        RAISE_APPLICATION_ERROR(-20003, 'Data_envio não pode ser futura.');
    END IF;
END;
/
-- TABELA Promocao
CREATE TABLE Promocao (
    ID_promocao  NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ID_livro     NUMBER NOT NULL,
    ID_cliente   NUMBER NOT NULL,
    Duracao      NUMBER NOT NULL,
    Data_inicio  DATE NOT NULL,
    Data_fim     DATE NOT NULL,

    CONSTRAINT PK_Promocao PRIMARY KEY (ID_promocao),
    CONSTRAINT FK_Promocao_Livro   FOREIGN KEY (ID_livro)   REFERENCES Livro(ID_livro),
    CONSTRAINT FK_Promocao_Cliente FOREIGN KEY (ID_cliente) REFERENCES Cliente(ID_cliente),
    CONSTRAINT CK_Promocao_Duracao CHECK (Duracao > 0),
    CONSTRAINT CK_Promocao_Datas   CHECK (Data_fim > Data_inicio),
    CONSTRAINT CK_Promocao_Dur_Coerente CHECK (ROUND(Data_fim - Data_inicio) = Duracao)
);
/
-- TRIGGER: impedir Data_inicio no passado
CREATE OR REPLACE TRIGGER trg_promocao_datas
BEFORE INSERT OR UPDATE ON Promocao
FOR EACH ROW
BEGIN
    IF :NEW.Data_inicio < TRUNC(SYSDATE) THEN
        RAISE_APPLICATION_ERROR(-20004, 'Data_inicio deve ser hoje ou futura.');
    END IF;
END;
/
-- TABELA Aquisicao
CREATE TABLE Aquisicao (
    ID_aquisicao   NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CNPJ_fornecedor VARCHAR2(18) NOT NULL,
    ID_livro        NUMBER NOT NULL,
    ID_funcionario  NUMBER NOT NULL,
    Data_aquisicao  DATE NOT NULL,
    Quantidade      NUMBER NOT NULL,
    Valor_unitario  NUMBER(10,2) NOT NULL,

    CONSTRAINT PK_Aquisicao PRIMARY KEY (ID_aquisicao),
    CONSTRAINT FK_Aquisicao_Fornecedor FOREIGN KEY (CNPJ_fornecedor) REFERENCES Fornecedor(CNPJ),
    CONSTRAINT FK_Aquisicao_Livro      FOREIGN KEY (ID_livro)        REFERENCES Livro(ID_livro),
    CONSTRAINT FK_Aquisicao_Func       FOREIGN KEY (ID_funcionario)  REFERENCES Funcionario(ID_funcionario),
    CONSTRAINT CK_Aquisicao_Qtd   CHECK (Quantidade > 0),
    CONSTRAINT CK_Aquisicao_Valor CHECK (Valor_unitario > 0)
);
/
-- TRIGGER: impedir Data_aquisicao futura
CREATE OR REPLACE TRIGGER trg_aquisicao_data
BEFORE INSERT OR UPDATE ON Aquisicao
FOR EACH ROW
BEGIN
    IF :NEW.Data_aquisicao > TRUNC(SYSDATE) THEN
        RAISE_APPLICATION_ERROR(-20005, 'Data_aquisicao não pode ser futura.');
    END IF;
END;
/
-- TABELA Contrato
CREATE TABLE Contrato (
    ID_contrato   NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ID_cliente    NUMBER NOT NULL,
    ID_funcionario NUMBER NOT NULL,
    ID_livro      NUMBER NOT NULL,
    Valor         NUMBER(10,2) NOT NULL,
    Data_contrato DATE NOT NULL,

    CONSTRAINT PK_Contrato PRIMARY KEY (ID_contrato),
    CONSTRAINT FK_Contrato_Cliente FOREIGN KEY (ID_cliente) REFERENCES Cliente(ID_cliente),
    CONSTRAINT FK_Contrato_Func    FOREIGN KEY (ID_funcionario) REFERENCES Funcionario(ID_funcionario),
    CONSTRAINT FK_Contrato_Livro   FOREIGN KEY (ID_livro) REFERENCES Livro(ID_livro),
    CONSTRAINT CK_Contrato_Valor   CHECK (Valor > 0)
);
/
-- TRIGGER: cliente deve ser PJ + impedir Data_contrato futura
CREATE OR REPLACE TRIGGER trg_contrato_validacoes
BEFORE INSERT OR UPDATE ON Contrato
FOR EACH ROW
DECLARE
    v_tipo CHAR(1);
BEGIN
    SELECT Tipo INTO v_tipo FROM Cliente WHERE ID_cliente = :NEW.ID_cliente;
    IF v_tipo <> 'J' THEN
        RAISE_APPLICATION_ERROR(-20006, 'Somente clientes PJ podem ter contratos.');
    END IF;

    IF :NEW.Data_contrato > TRUNC(SYSDATE) THEN
        RAISE_APPLICATION_ERROR(-20007, 'Data_contrato não pode ser futura.');
    END IF;
END;
/
-- TABELA Reserva
CREATE TABLE Reserva (
    ID_reserva  NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ID_cliente  NUMBER NOT NULL,
    ID_livro    NUMBER NOT NULL,
    Taxa        NUMBER(10,2) NOT NULL,
    Data_reserva DATE NOT NULL,
    Status      VARCHAR2(20) DEFAULT 'Ativa',

    CONSTRAINT PK_Reserva PRIMARY KEY (ID_reserva),
    CONSTRAINT FK_Reserva_Cliente FOREIGN KEY (ID_cliente) REFERENCES Cliente(ID_cliente),
    CONSTRAINT FK_Reserva_Livro   FOREIGN KEY (ID_livro)   REFERENCES Livro(ID_livro),
    CONSTRAINT CK_Reserva_Taxa    CHECK (Taxa >= 0),
    CONSTRAINT CK_Reserva_Status  CHECK (Status IN ('Ativa','Finalizada','Cancelada')),
    CONSTRAINT UK_Reserva_Cliente_Livro UNIQUE (ID_cliente, ID_livro)
);
/
-- TRIGGER: cliente deve ser PF + impedir Data_reserva futura
CREATE OR REPLACE TRIGGER trg_reserva_validacoes
BEFORE INSERT OR UPDATE ON Reserva
FOR EACH ROW
DECLARE
    v_tipo CHAR(1);
BEGIN
    SELECT Tipo INTO v_tipo FROM Cliente WHERE ID_cliente = :NEW.ID_cliente;
    IF v_tipo <> 'F' THEN
        RAISE_APPLICATION_ERROR(-20008, 'Somente clientes PF podem fazer reservas.');
    END IF;

    IF :NEW.Data_reserva > TRUNC(SYSDATE) THEN
        RAISE_APPLICATION_ERROR(-20009, 'Data_reserva não pode ser futura.');
    END IF;
END;
/
